---
title: "3/23/2020 Update"
author: "William Norfolk"
date: "3/24/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(maps)
library(usmap)
```

```{r}
covid_master <- readRDS("../clean_covid_data.rds")
```


```{r}
covid_3_23 <- readr::read_csv("../raw_data/covid_03-23-2020_update.csv")
```


```{r}
us_only <- subset(covid_3_23, Country_Region == "US")
```

```{r}
agg_cases_3_23 <- aggregate(Confirmed ~ Province_State, us_only, sum)
agg_deaths_3_23 <- aggregate(Deaths ~ Province_State, us_only, sum)
agg_recovered_3_23 <- aggregate(Recovered ~ Province_State, us_only, sum)
```

```{r}
merge_aggs <- merge(agg_cases_3_23, agg_deaths_3_23, by = c("Province_State"))
merge_final <- merge(merge_aggs, agg_recovered_3_23, by = c("Province_State"))
```

```{r}
#Match up names
fix_names <- merge_final %>% rename(cases_3_23 = Confirmed, deaths_3_23 = Deaths, recov_3_23 = Recovered)
```

```{r}
#Remove observations not from contigious US and AK and HI

clean_obs <- fix_names[!(fix_names$Province_State == "Diamond Princess" | fix_names$Province_State == "Grand Princess" | fix_names$Province_State == "Guam" | fix_names$Province_State == "Puerto Rico" | fix_names$Province_State == "United States Virgin Islands" | fix_names$Province_State == "US" | fix_names$Province_State == "American Samoa" | fix_names$Province_State == "Northern Mariana Islands" | fix_names$Province_State == "Virgin Islands" | fix_names$Province_State == "Wuhan Evacuee"),]
```

```{r}
#Merge new data to master set.
merge_new <- merge(clean_obs, covid_master)
```

```{r}
#merge_new <- merge_new %>% dplyr::select(c(-cases_3_23.x, -deaths_3_23.x, -recov_3_23.x, -cases_3_23.y, -deaths_3_23.y, -recov_3_23.y))
```

```{r}
#Change total column value each time
merge_new <- merge_new[, c(1,5,6,7,8:19,2,3,4)]
```


```{r}
#save master clean data to add new values
#Only uncommnet to update RDS

#saveRDS(merge_new, file = "./clean_covid_data.rds")
```

#### Barcharts

```{r}
top_10_cases <- tail(sort(merge_new$cases_3_23),10)
top_10_cases
```

```{r}
#subset top 10 cases
ext_1 <- subset(merge_new, cases_3_23 == "772")
ext_2 <- subset(merge_new, cases_3_23 == "777")
ext_3 <- subset(merge_new, cases_3_23 == "1172")
ext_4 <- subset(merge_new, cases_3_23 == "1227")
ext_5 <- subset(merge_new, cases_3_23 == "1285")
ext_6 <- subset(merge_new, cases_3_23 == "1329")
ext_7 <- subset(merge_new, cases_3_23 == "2108")
ext_8 <- subset(merge_new, cases_3_23 == "2221")
ext_9 <- subset(merge_new, cases_3_23 == "2844")
ext_10 <- subset(merge_new, cases_3_23 == "20884")

top_ten_cases <- rbind(ext_1, ext_2, ext_3, ext_4, ext_5, ext_6, ext_7, ext_8, ext_9, ext_10)
```

```{r}
#make bar chart
cases_3_23_bar <- ggplot(top_ten_cases, aes(x = reorder(Province_State, -cases_3_23), cases_3_23)) + geom_bar(aes(fill = reorder(Province_State, -cases_3_23)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),
  panel.border = element_blank(),   
  axis.title.y = element_text(size = 12),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Confirmed COVID-19 Cases") + ggtitle("Top Ten Confirmed COVID-19 Cases by State 3/23/2020") +
  
   geom_text(aes(label = cases_3_23), size = 4, position = position_stack(vjust = 0.8))

cases_3_23_bar
```

```{r}
ggsave(filename = "../bar_charts/cases_3_23_bar.png", plot = cases_3_23_bar)
```

#### Heatmaps


```{r}
#mapping code example for 3/22/20 confirmed cases
case_state_3_23 <- plot_usmap(data = merge_new, values = "cases_3_23", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Total Cases", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "COVID-19 Confirmed Cases by State", subtitle = "Data as of: 3/23/2020")

case_state_3_23
```

```{r}
ggsave(filename = "../heat_maps/case_state_3_23.png", plot = case_state_3_23)
```

## Percent Increase Examples

```{r}
#To determine percent increase from prior day, include only last two observations
#UPDATE DAILY

only_22_and_23 <- subset(merge_new, select = c(Province_State, cases_3_22, cases_3_23, fips, total_pop))
```


```{r}
#add percent increase
#UPDATE DAILY with new data

only_22_and_23 <- only_22_and_23 %>% dplyr::mutate(percent_increase = (cases_3_23 - cases_3_22) / cases_3_22 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_22_to_23 <- plot_usmap(data = only_22_and_23, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 3/22/2020-3/23/2020")

p_increase_cases_22_to_23
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_22_to_23.png", plot = p_increase_cases_22_to_23)
```

## Cases per 100K Population

```{r}
#convert pop to thousands

only_22_and_23 <- only_22_and_23 %>% dplyr::mutate(cases_100k_23 = (cases_3_23 / total_pop) *100000)
  
only_22_and_23 <- only_22_and_23 %>% dplyr::mutate(cases_100k_22 = (cases_3_22 / total_pop) * 100000)

only_22_and_23 <- only_22_and_23 %>% dplyr::mutate(case_100k_increase = (cases_100k_23 - cases_100k_22) / cases_100k_23 *100)

```

```{r}
#total cases per 100k population as of 3/23

cases_100k_3_23 <- plot_usmap(data = only_22_and_23, values = "cases_100k_23", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Cases/100k Population", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "COVID-19 Confirmed Cases Per 100K Individuals by State", subtitle = "Data as of: 3/23/2020")

cases_100k_3_23
```

```{r}
ggsave(filename = "../heat_maps/cases_100k_3_23.png", plot = cases_100k_3_23)
```

```{r}
tail(sort(only_22_and_23$cases_100k_23 ),10)

```


```{r}
#subset top 10 100K
extk_1 <- subset(only_22_and_23, Province_State == "Massachusetts")
extk_2 <- subset(only_22_and_23, Province_State == "Connecticut")
extk_3 <- subset(only_22_and_23, Province_State == "Vermont")
extk_4 <- subset(only_22_and_23, Province_State == "Colorado")
extk_5 <- subset(only_22_and_23, Province_State == "Michigan")
extk_6 <- subset(only_22_and_23, Province_State == "District of Columbia")
extk_7 <- subset(only_22_and_23, Province_State == "Louisiana")
extk_8 <- subset(only_22_and_23, Province_State == "Washington")
extk_9 <- subset(only_22_and_23, Province_State == "New Jersey")
extk_10 <- subset(only_22_and_23, Province_State == "New York")

top_ten_cases_100k <- rbind(extk_1, extk_2, extk_3, extk_4, extk_5, extk_6, extk_7, extk_8, extk_9, extk_10)
```

```{r}
#make bar chart
cases_100k_3_23_bar <- ggplot(top_ten_cases_100k, aes(x = reorder(Province_State, -cases_100k_23), cases_100k_23)) + geom_bar(aes(fill = reorder(Province_State, -cases_100k_23)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),
  panel.border = element_blank(),   
  axis.title.y = element_text(size = 12),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Cases Per 100K Individuals") + ggtitle("Top Ten COVID-19 Confirmed Cases Per 100K Individuals by State 3/23/2020") +
  
   geom_text(aes(label = round(cases_100k_23, 1)), size = 4, position = position_stack(vjust = 0.8))

cases_100k_3_23_bar
```

```{r}
ggsave(filename = "../bar_charts/cases_100k_3_23_bar.png", plot = cases_100k_3_23_bar)
```

```{r}
tail(sort(only_22_and_23$percent_increase ),10)

```

```{r}
#subset top 10 cases
extp_1 <- subset(only_22_and_23, Province_State == "New Mexico")
extp_2 <- subset(only_22_and_23, Province_State == "Florida")
extp_3 <- subset(only_22_and_23, Province_State == "Colorado")
extp_4 <- subset(only_22_and_23, Province_State == "New Jersey")
extp_5 <- subset(only_22_and_23, Province_State == "South Carolina")
extp_6 <- subset(only_22_and_23, Province_State == "Arizona")
extp_7 <- subset(only_22_and_23, Province_State == "New Hampshire")
extp_8 <- subset(only_22_and_23, Province_State == "Idaho")
extp_9 <- subset(only_22_and_23, Province_State == "Connecticut")
extp_10 <- subset(only_22_and_23, Province_State == "Missouri")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
perc_increase_3_23_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),
  panel.border = element_blank(),   
  axis.title.y = element_text(size = 12),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State from 3/22/20-3/23/20") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

perc_increase_3_23_bar
```

```{r}
ggsave(filename = "../bar_charts/perc_increase_3_23_bar.png", plot = perc_increase_3_23_bar)
```


