---
title: "covid_add_3_19_to_22_2020_data_old_format"
author: "William Norfolk"
date: "3/23/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(maps)
library(usmap)
```

```{r}
covid_3_19 <- readr::read_csv("../raw_data/covid_03-19-2020_update.csv")
covid_3_20 <- readr::read_csv("../raw_data/covid_03-20-2020_update.csv")
covid_3_21 <- readr::read_csv("../raw_data/covid_03-21-2020_update.csv")
covid_3_22 <- readr::read_csv("../raw_data/covid_03-22-2020_update.csv")
```

```{r}
#Fix annoying names
covid_3_19 <- covid_3_19 %>% rename(cases_3_19 = Confirmed, deaths_3_19 = Deaths, recov_3_19 = Recovered)
covid_3_20 <- covid_3_20 %>% rename(cases_3_20 = Confirmed, deaths_3_20 = Deaths, recov_3_20 = Recovered)
covid_3_21 <- covid_3_21 %>% rename(cases_3_21 = Confirmed, deaths_3_21 = Deaths, recov_3_21 = Recovered)
covid_3_22 <- covid_3_22 %>% rename(cases_3_22 = Confirmed, deaths_3_22 = Deaths, recov_3_22 = Recovered)

```

```{r}
covid_3_19 <- covid_3_19 %>% dplyr::select(-`Last Update`, -Latitude, -Longitude)
covid_3_20 <- covid_3_20 %>% dplyr::select(-`Last Update`, -Latitude, -Longitude)
covid_3_21 <- covid_3_21 %>% dplyr::select(-`Last Update`, -Latitude, -Longitude)
covid_3_22 <- covid_3_22 %>% dplyr::select(-`Last Update`, -Latitude, -Longitude)
```


```{r}
merge_19_and_20 <- merge(covid_3_19, covid_3_20, by = c("Province/State","Country/Region"))
```

```{r}
merge_22_and_21 <- merge(covid_3_21, covid_3_22, by = c("Province/State","Country/Region"))
```

```{r}
merge_all_up_to_3_22 <- merge(merge_19_and_20, merge_22_and_21, by = c("Province/State","Country/Region"))
```

```{r}
us_only <- subset(merge_all_up_to_3_22, `Country/Region` == "US")
```

```{r}
clean_us_only <- us_only[!(us_only$`Province/State` == "Diamond Princess" | us_only$`Province/State` == "Grand Princess" | us_only$`Province/State` == "Guam" | us_only$`Province/State` == "Puerto Rico" | us_only$`Province/State` == "United States Virgin Islands" | us_only$`Province/State` == "US"),]
```

```{r}
#Add total populaton
#As of July 1 2019 Estimates by US Census
add_total_pop <- clean_us_only %>% dplyr::mutate(total_pop = recode(`Province/State`,
                                                                 "Alabama" = 4903185,
                                                                 "Alaska" = 731545,
                                                                 "Arizona" = 7278717,
                                                                 "Arkansas" = 3017804,
                                                                 "California" = 39512223,
                                                                 "Colorado" = 5758736,
                                                                 "Connecticut" = 3565287,
                                                                 "Delaware" = 973764,
                                                                 "District of Columbia" = 705749,
                                                                 "Florida" = 21477737,
                                                                 "Georgia" = 10617423,
                                                                 "Hawaii" = 1415872,
                                                                 "Idaho" = 1787065,
                                                                 "Illinois" = 12671821,
                                                                 "Indiana" = 6732219,
                                                                 "Iowa" = 3155070,
                                                                 "Kansas" = 2913314,
                                                                 "Kentucky" = 4467673,
                                                                 "Louisiana" = 4648794,
                                                                 "Maine" = 1344212,
                                                                 "Maryland" = 6045680,
                                                                 "Massachusetts" = 6892503,
                                                                 "Michigan" = 9986857,
                                                                 "Minnesota" = 5639632,
                                                                 "Mississippi" = 2976149,
                                                                 "Missouri" = 6137428,
                                                                 "Montana" = 1068778,
                                                                 "Nebraska" = 1934408,
                                                                 "Nevada" = 3080156,
                                                                 "New Hampshire" = 1359711,
                                                                 "New Jersey" = 8882190,
                                                                 "New Mexico" = 2096829,
                                                                 "New York" = 19453561,
                                                                 "North Carolina" = 10488084,
                                                                 "North Dakota" = 762062,
                                                                 "Ohio" = 11689100,
                                                                 "Oklahoma" = 3956971,
                                                                 "Oregon" = 4217737,
                                                                 "Pennsylvania" = 12801989,
                                                                 "Rhode Island" = 1059361,
                                                                 "South Carolina" = 5148714,
                                                                 "South Dakota" = 884659,
                                                                 "Tennessee" = 6829174,
                                                                 "Texas" = 28995881,
                                                                 "Utah" = 3205958,
                                                                 "Vermont" = 623989,
                                                                 "Virginia" = 8535519,
                                                                 "Washington" = 7614893,
                                                                 "West Virginia" = 1792147,
                                                                 "Wisconsin" = 5822434, 
                                                                 "Wyoming" = 578759))
```

```{r}
#add FIPS codes for map

add_fips <- add_total_pop %>% dplyr::mutate(fips = recode(`Province/State`,
                                                                 "Alabama" = "01",
                                                                 "Alaska" = "02",
                                                                 "Arizona" = "04",
                                                                 "Arkansas" = "05",
                                                                 "California" = "06",
                                                                 "Colorado" = "08",
                                                                 "Connecticut" = "09",
                                                                 "Delaware" = "10",
                                                                 "District of Columbia" = "11",
                                                                 "Florida" = "12",
                                                                 "Georgia" = "13",
                                                                 "Hawaii" = "15",
                                                                 "Idaho" = "16",
                                                                 "Illinois" = "17",
                                                                 "Indiana" = "18",
                                                                 "Iowa" = "19",
                                                                 "Kansas" = "20",
                                                                 "Kentucky" = "21",
                                                                 "Louisiana" = "22",
                                                                 "Maine" = "23",
                                                                 "Maryland" = "24",
                                                                 "Massachusetts" = "25",
                                                                 "Michigan" = "26",
                                                                 "Minnesota" = "27",
                                                                 "Mississippi" = "28",
                                                                 "Missouri" = "29",
                                                                 "Montana" = "30",
                                                                 "Nebraska" = "31",
                                                                 "Nevada" = "32",
                                                                 "New Hampshire" = "33",
                                                                 "New Jersey" = "34",
                                                                 "New Mexico" = "35",
                                                                 "New York" = "36",
                                                                 "North Carolina" = "37",
                                                                 "North Dakota" = "38",
                                                                 "Ohio" = "39",
                                                                 "Oklahoma" = "40",
                                                                 "Oregon" = "41",
                                                                 "Pennsylvania" = "42",
                                                                 "Rhode Island" = "44",
                                                                 "South Carolina" = "45",
                                                                 "South Dakota" = "46",
                                                                 "Tennessee" = "47",
                                                                 "Texas" = "48",
                                                                 "Utah" = "49",
                                                                 "Vermont" = "50",
                                                                 "Virginia" = "51",
                                                                 "Washington" = "53",
                                                                 "West Virginia" = "54",
                                                                 "Wisconsin" = "55", 
                                                                 "Wyoming" = "56"))
```

```{r}
fix_state_var <- add_fips %>% rename(Province_State = `Province/State`)
```

```{r}
reorder_vars <- fix_state_var[, c(1,2,15,16,3,4,5,6,7,8,9,10,11,12,13,14)]
```



```{r}
#save master clean data to add new values
#saveRDS(reorder_vars, file = "./clean_covid_data.rds")
```


#### Barcharts

```{r}
top_10_cases <- tail(sort(reorder_vars$cases_3_22),10)
top_10_cases
```

```{r}
#subset top 10 cases
ext_1 <- subset(reorder_vars, cases_3_22 == "627")
ext_2 <- subset(reorder_vars, cases_3_22 == "646")
ext_3 <- subset(reorder_vars, cases_3_22 == "830")
ext_4 <- subset(reorder_vars, cases_3_22 == "837")
ext_5 <- subset(reorder_vars, cases_3_22 == "1037")
ext_6 <- subset(reorder_vars, cases_3_22 == "1049")
ext_7 <- subset(reorder_vars, cases_3_22 == "1642")
ext_8 <- subset(reorder_vars, cases_3_22 == "1914")
ext_9 <- subset(reorder_vars, cases_3_22 == "1996")
ext_10 <- subset(reorder_vars, cases_3_22 == "15793")

top_ten_cases <- rbind(ext_1, ext_2, ext_3, ext_4, ext_5, ext_6, ext_7, ext_8, ext_9, ext_10)
```

```{r}
#make bar chart
cases_3_22_bar <- ggplot(top_ten_cases, aes(x = reorder(Province_State, -cases_3_22), cases_3_22)) + geom_bar(aes(fill = reorder(Province_State, - cases_3_22)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=10),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Confirmed COVID-19 Cases") + ggtitle("Top Ten Confirmed COVID-19 Cases by State 3/22/2020") +
  
   geom_text(aes(label = cases_3_22), size = 4, position = position_stack(vjust = 0.8))

cases_3_22_bar
```

```{r}
ggsave(filename = "../bar_charts/cases_3_22_bar.png", plot = cases_3_22_bar)
```











## Paste this map code into daily uploads to generate new heatmaps with additional data. 


```{r}
#mapping code example for 3/22/20 confirmed cases
case_state_3_22 <- plot_usmap(data = add_fips, values = "cases_3_22", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Total Cases", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "COVID-19 Confirmed Cases by State", subtitle = "Data as of: 3/22/2020")

case_state_3_22
```

## Percent Increase Examples

```{r}
#To determine percent increase from prior day, include only last two observations
#UPDATE DAILY

only_21_and_22 <- subset(add_fips, select = c(`Province/State`, `Country/Region`, cases_3_22, cases_3_21, fips, total_pop))
```


```{r}
#add percent increase
#UPDATE DAILY with new data

only_21_and_22 <- only_21_and_22 %>% dplyr::mutate(percent_increase = (cases_3_22 - cases_3_21) / cases_3_22 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_21_to_22 <- plot_usmap(data = only_21_and_22, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 3/21/2020-3/22/2020")

p_increase_cases_21_to_22
```


## Cases per 100K Population

```{r}
#convert pop to thousands

only_21_and_22 <- only_21_and_22 %>% dplyr::mutate(cases_100k_22 = (cases_3_22 / total_pop) *100000)
  
only_21_and_22 <- only_21_and_22 %>% dplyr::mutate(cases_100k_21 = (cases_3_21 / total_pop) * 100000)

only_21_and_22 <- only_21_and_22 %>% dplyr::mutate(case_100k_increase = (cases_100k_22 - cases_100k_21) / cases_100k_22 *100)

```

```{r}
#total cases per 100k population as of 3/22

cases_100k_3_22 <- plot_usmap(data = only_21_and_22, values = "cases_100k_22", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Cases/100k Population", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "COVID-19 Confirmed Cases Per 100K Individuals by State", subtitle = "Data as of: 3/22/2020")

cases_100k_3_22
```

```{r}
tail(sort(only_21_and_22$cases_100k_22 ),10)

```


```{r}
#subset top 10 100K
extk_1 <- subset(only_21_and_22, `Province/State` == "Colorado")
extk_2 <- subset(only_21_and_22, `Province/State` == "Illinois")
extk_3 <- subset(only_21_and_22, `Province/State` == "Vermont")
extk_4 <- subset(only_21_and_22, `Province/State` == "Massachusetts")
extk_5 <- subset(only_21_and_22, `Province/State` == "Michigan")
extk_6 <- subset(only_21_and_22, `Province/State` == "District of Columbia")
extk_7 <- subset(only_21_and_22, `Province/State` == "Louisiana")
extk_8 <- subset(only_21_and_22, `Province/State` == "New Jersey")
extk_9 <- subset(only_21_and_22, `Province/State` == "Washington")
extk_10 <- subset(only_21_and_22, `Province/State` == "New York")

top_ten_cases_100k <- rbind(extk_1, extk_2, extk_3, extk_4, extk_5, extk_6, extk_7, extk_8, extk_9, extk_10)
```

```{r}
#make bar chart
cases_100k_3_22_bar <- ggplot(top_ten_cases_100k, aes(x = reorder(`Province/State`, -cases_100k_22), cases_100k_22)) + geom_bar(aes(fill = reorder(`Province/State`, -cases_100k_22)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=10),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Cases Per 100K Individuals") + ggtitle("Top Ten COVID-19 Confirmed Cases Per 100K Individuals by State 3/22/2020") +
  
   geom_text(aes(label = round(cases_100k_22, 1)), size = 4, position = position_stack(vjust = 0.8))

cases_100k_3_22_bar
```

```{r}
ggsave(filename = "../bar_charts/cases_100k_3_22_bar.png", plot = cases_100k_3_22_bar)
```



```{r}
tail(sort(only_21_and_22$percent_increase ),10)

```

```{r}
#subset top 10 cases
extp_1 <- subset(only_21_and_22, `Province/State` == "Virginia")
extp_2 <- subset(only_21_and_22, `Province/State` == "Louisiana")
extp_3 <- subset(only_21_and_22, `Province/State` == "Ohio")
extp_4 <- subset(only_21_and_22, `Province/State` == "New Jersey")
extp_5 <- subset(only_21_and_22, `Province/State` == "Montana")
extp_6 <- subset(only_21_and_22, `Province/State` == "Mississippi")
extp_7 <- subset(only_21_and_22, `Province/State` == "South Dakota")
extp_8 <- subset(only_21_and_22, `Province/State` == "West Virginia")
extp_9 <- subset(only_21_and_22, `Province/State` == "Indiana")
extp_10 <- subset(only_21_and_22, `Province/State` == "Vermont")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
perc_increase_3_22_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(`Province/State`, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(`Province/State`, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=10),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State from 3/21/20-3/22/20") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

perc_increase_3_22_bar
```

```{r}
ggsave(filename = "../bar_charts/perc_increase_3_22_bar.png", plot = perc_increase_3_22_bar)
```


