---
title: "3/24/2020 Update"
author: "William Norfolk"
date: "3/24/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(maps)
library(usmap)
library(viridis)
```

```{r}
#Load masterdata
covid_master <- readRDS("../clean_covid_data.rds")
```


```{r}
#load new data from update. MODIFY: data object date
covid_3_24 <- readr::read_csv("../raw_data/covid_03-24-2020_update.csv")
```

```{r}
#subset new data to only US observations. MODIFY: data object date
us_only <- subset(covid_3_24, Country_Region == "US")
```

```{r}
#aggregate deaths, cases, and recoveries for new data. 
agg_cases <- aggregate(Confirmed ~ Province_State, us_only, sum)
agg_deaths <- aggregate(Deaths ~ Province_State, us_only, sum)
agg_recovered <- aggregate(Recovered ~ Province_State, us_only, sum)
```

```{r}
#merge aggregate datasets
merge_aggs <- merge(agg_cases, agg_deaths, by = c("Province_State"))
merge_final <- merge(merge_aggs, agg_recovered, by = c("Province_State"))
```

```{r}
#Match up names to master data format. MODIFY: variable dates
fix_names <- merge_final %>% rename(cases_3_24 = Confirmed, deaths_3_24 = Deaths, recov_3_24 = Recovered)
```

```{r}
#Remove observations not from contigious US and AK and HI
#Should always be 51 observations (50 states + DC) and 4 variables

clean_obs <- fix_names[!(fix_names$Province_State == "Diamond Princess" | fix_names$Province_State == "Grand Princess" | fix_names$Province_State == "Guam" | fix_names$Province_State == "Puerto Rico" | fix_names$Province_State == "United States Virgin Islands" | fix_names$Province_State == "US" | fix_names$Province_State == "American Samoa" | fix_names$Province_State == "Northern Mariana Islands" | fix_names$Province_State == "Virgin Islands" | fix_names$Province_State == "Wuhan Evacuee" | fix_names$Province_State == "Recovered"),]
```

```{r}
#Merge new data into master set.
merge_new <- merge(clean_obs, covid_master)
```

```{r}
#Move variables into proper chronological order
#MODIFY: total variable value each time
merge_new <- merge_new[, c(1,5,6,7,8:22,2,3,4)]
```

```{r}
#save master clean data to add new values
#Only uncommnet to update RDS

#saveRDS(merge_new, file = "../clean_covid_data.rds")
```

## GA ONLY

```{r}
ga_only <- subset(covid_3_24, Province_State == "Georgia")

```

```{r}
ga_pull_vars <- ga_only %>% dplyr::select(c(-Country_Region, -Last_Update, -Lat, -Long_, -Combined_Key))
```

```{r}
#Match up names
ga_fix_vars <- ga_pull_vars %>% rename(ga_cases_3_24 = Confirmed, ga_deaths_3_24 = Deaths, ga_recov_3_24 = Recovered, ga_active_3_24 = Active, fips = FIPS)
```

```{r}
ga_master <- readRDS("../ga_only_clean_data.rds")
```

```{r}
#Merge new data into master set.
ga_master <- merge(ga_master, ga_fix_vars)
```

```{r}
#Add total populaton
#As of July 1 2019 Estimates by US Census
ga_master <- ga_master %>% dplyr::mutate(county_pop = recode(Admin2,
                                                                 "Fulton" = 1021902,
                                                                 "Gwinnett" = 902298,
                                                                 "Cobb" = 745057,
                                                                 "DeKalb" = 743187,
                                                                 "Chatham" = 287049,
                                                                 "Clayton" = 278666,
                                                                 "Cherokee" = 241910,
                                                                 "Henry" = 221307,
                                                                 "Forsyth" = 219880,
                                                                 "Richmond" = 201463,
                                                                 "Muscogee" = 196670,
                                                                 "Hall" = 195961,
                                                                 "Paulding" = 155840,
                                                                 "Bibb" = 153490,
                                                                 "Huston" = 151682,
                                                                 "Columbia" = 147295,
                                                                 "Douglas" = 141840,
                                                                 "Coweta" = 140516,
                                                                 "Clarke" = 124602,
                                                                 "Carroll" = 116022,
                                                                 "Lowndes" = 114582,
                                                                 "Fayette" = 111369,
                                                                 "Newton" = 106497,
                                                                 "Whitfield" = 103849,
                                                                 "Bartow" = 103620,
                                                                 "Floyd" = 96824,
                                                                 "Dougherty" = 91049,
                                                                 "Walton" = 90132,
                                                                 "Rockdale" = 89011,
                                                                 "Glynn" = 83974,
                                                                 "Barrow" = 76887,
                                                                 "Bulloch" = 74782,
                                                                 "Troup" = 69774,
                                                                 "Walker" = 68824,
                                                                 "Catoosa" = 66299,
                                                                 "Jackson" = 65755,
                                                                 "Spalding" = 64719,
                                                                 "Liberty" = 62108,
                                                                 "Effingham" = 58689,
                                                                 "Gordon" = 56790,
                                                                 "Camden" = 52714,
                                                                 "Laurens" = 47418,
                                                                 "Colquitt" = 45606,
                                                                 "Baldwin" = 45286,
                                                                 "Thomas" = 44730,
                                                                 "Habersham" = 44289,
                                                                 "Coffee" = 42961,
                                                                 "Polk" = 41621,
                                                                 "Tift" = 40510,
                                                                 "Murray" = 39557, 
                                                                 "Oconee" = 37017,
                                                                 "Bryan" = 35885,
                                                                 "Ware" = 35599,
                                                             "Harris" = 33590,
                                                             "Lumpkin" = 31951,
                                                             "Pickens" = 30832,
                                                             "Sumter" = 30352,
                                                             "Gilmer" = 29922,
                                                             "Wayne" = 29767,
                                                             "Lee" = 29348,
                                                             "Haralson" = 28956,
                                                             "White" = 28928,
                                                             "Madison" = 28900,
                                                             "Jones" = 28548,
                                                             "Toombs" = 27048,
                                                             "Monroe" = 27010,
                                                             "Peach" = 26966,
                                                             "Decatur" = 26833,
                                                             "Upson" = 26216,
                                                             "Stephens" = 25676,
                                                             "Hart" = 25631,
                                                             "Tattnall" = 25353,
                                                             "Grady" = 24926,
                                                             "Fannin" = 24925,
                                                             "Chattooga" = 24817,
                                                             "Dawson" = 23861,
                                                             "Butts" = 23750,
                                                             "Crisp" = 22846,
                                                             "Union" = 22775,
                                                             "Burke" = 22550,
                                                             "Franklin" = 22514,
                                                             "Emanuel" = 22499,
                                                             "Mitchell" = 22432,
                                                             "Putnam" = 21503,
                                                             "McDuffie" = 21498,
                                                             "Meriwether" = 21113,
                                                             "Dodge" = 20919,
                                                             "Worth" = 20656,
                                                             "Washington" = 20461,
                                                             "Elbert" = 19212,
                                                             "Pierce" = 19164,
                                                             "Berrien" = 19025,
                                                             "Brantley" = 18561,
                                                             "Lamar" = 18513,
                                                             "Banks" = 18510,
                                                             "Appling" = 18454,
                                                             "Morgan" = 18235,
                                                             "Long" = 18156,
                                                             "Pike" = 18082,
                                                             "Cook" = 17184,
                                                             "Ben Hill" = 17154,
                                                             "Greene" = 16976,
                                                             "Rabun" = 16457,
                                                             "Dade" = 16227,
                                                             "Telfair" = 16115,
                                                             "Jefferson" = 15772,
                                                             "Brooks" = 15622,
                                                             "Jeff Davis" = 14991,
                                                             "Oglethorpe" = 14784,
                                                             "McIntosh" = 14120,
                                                             "Screven" = 13990,
                                                             "Dooly" = 13905,
                                                             "Jasper" = 13784,
                                                             "Macon" = 13480,
                                                             "Charlton" = 12983,
                                                             "Bleckley" = 12775,
                                                             "Crawford" = 12344,
                                                             "Heard" = 11677,
                                                             "Towns" = 11417,
                                                             "Pulaski" = 11295,
                                                             "Bacon" = 11228,
                                                             "Candler" = 10827,
                                                             "Chattahoochee" = 10767,
                                                             "Evans" = 10727,
                                                             "Lanier" = 10366,
                                                             "Early" = 10348,
                                                             "Wilkes" = 9884,
                                                             "Johnson" = 9730,
                                                             "Irwin" = 9268,
                                                             "Wilkinson" = 9078,
                                                             "Montgomery" = 9036,
                                                             "Terrell" = 8859,
                                                             "Wilcox" = 8846,
                                                             "Jenkins" = 8827,
                                                             "Hancock" = 8535,
                                                             "Marion" = 8484,
                                                             "Seminole" = 8437,
                                                             "Twiggs" = 8284,
                                                             "Atkinson" = 8265,
                                                             "Taylor" = 8193,
                                                             "Turner" = 7962,
                                                             "Wheeler" = 7939,
                                                             "Lincoln" = 7799,
                                                             "Randolph" = 7087,
                                                             "Treutlen" = 6777,
                                                             "Clinch" = 6743,
                                                             "Calhoun" = 6428,
                                                             "Talbot" = 6378,
                                                             "Stewart" = 6042,
                                                             "Miller" = 5836,
                                                             "Warren" = 5346,
                                                             "Schley" = 5211,
                                                             "Echols" = 3994,
                                                             "Baker" = 3189,
                                                             "Glascock" = 3009,
                                                             "Clay" = 3001,
                                                             "Webster" = 2613,
                                                             "Quitman" = 2276,
                                                             "Taliaferro" = 1665))
```

```{r}
#save master clean data to add new values
#Only uncommnet to update RDS

#saveRDS(ga_master, file = "../ga_only_clean_data.rds")
```


#### CHART START

```{r}
#Take a look at the top 10 cases
#MODIFY: cases variable for new date
top_10_cases <- tail(sort(merge_new$cases_3_24),10)
top_10_cases
```

```{r}
#subset top 10 cases
#MODIFY: use tail() results and paste into subset syntax, also modifty cases date value
ext_1 <- subset(merge_new, cases_3_24 == "1026")
ext_2 <- subset(merge_new, cases_3_24 == "1159")
ext_3 <- subset(merge_new, cases_3_24 == "1388")
ext_4 <- subset(merge_new, cases_3_24 == "1412")
ext_5 <- subset(merge_new, cases_3_24 == "1537")
ext_6 <- subset(merge_new, cases_3_24 == "1793")
ext_7 <- subset(merge_new, cases_3_24 == "2328")
ext_8 <- subset(merge_new, cases_3_24 == "2538")
ext_9 <- subset(merge_new, cases_3_24 == "3675")
ext_10 <- subset(merge_new, cases_3_24 == "25681")

top_ten_cases <- rbind(ext_1, ext_2, ext_3, ext_4, ext_5, ext_6, ext_7, ext_8, ext_9, ext_10)
```

```{r}
#make bar chart
#MODIFY: all cases variables to correct date and ggtitle
cases_3_24_bar <- ggplot(top_ten_cases, aes(x = reorder(Province_State, -cases_3_24), cases_3_24)) + geom_bar(aes(fill = reorder(Province_State, -cases_3_24)),stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),
  panel.border = element_blank(),   
  axis.title.y = element_text(size = 12),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Confirmed COVID-19 Cases") + ggtitle("Top Ten Confirmed COVID-19 Cases by State 3/24/2020") +
  
   geom_text(aes(label = cases_3_24), size = 4, position = position_stack(vjust = 0.8))

cases_3_24_bar 
```
```{r}
ggsave(filename = "../bar_charts/cases_3_24_bar.png", plot = cases_3_24_bar)
```

```{r}
#mapping code cases map
#MODIFY: cases variable date and all titles.

case_state_3_24 <- plot_usmap(data = merge_new, values = "cases_3_24", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Total Cases", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "COVID-19 Confirmed Cases by State", subtitle = "Data as of: 3/24/2020")

case_state_3_24
```

```{r}
ggsave(filename = "../heat_maps/case_state_3_24.png", plot = case_state_3_24)
```

## Percent Increase and 100k Code

```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_23_and_24 <- subset(merge_new, select = c(Province_State, cases_3_23, cases_3_24, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_23_and_24 <- only_23_and_24 %>% dplyr::mutate(percent_increase = (cases_3_24 - cases_3_23) / cases_3_23 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_23_to_24 <- plot_usmap(data = only_23_and_24, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 3/23/2020-3/24/2020")

p_increase_cases_23_to_24
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_23_to_24.png", plot = p_increase_cases_23_to_24)
```

```{r}
#convert pop to thousands
#MODIFY: object dates and variable dates

only_23_and_24 <- only_23_and_24 %>% dplyr::mutate(cases_100k_24 = (cases_3_24 / total_pop) *100000)
  
only_23_and_24 <- only_23_and_24 %>% dplyr::mutate(cases_100k_23 = (cases_3_23 / total_pop) * 100000)

only_23_and_24 <- only_23_and_24 %>% dplyr::mutate(case_100k_increase = (cases_100k_24 - cases_100k_23) / cases_100k_24 *100)

```

```{r}
#total cases per 100k population as of 3/23

cases_100k_3_24 <- plot_usmap(data = only_23_and_24, values = "cases_100k_24", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Cases/100k Population", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "COVID-19 Confirmed Cases Per 100K Individuals by State", subtitle = "Data as of: 3/24/2020")

cases_100k_3_24
```

```{r}
ggsave(filename = "../heat_maps/cases_100k_3_24.png", plot = cases_100k_3_24)
```

```{r}
#Take a look at the top 10 cases per 100k
#MODIFY: cases variable for new date
tail(sort(only_23_and_24$cases_100k_24 ),10)
```


```{r}
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extk_1 <- subset(only_23_and_24, Province_State == "Colorado")
extk_2 <- subset(only_23_and_24, Province_State == "Vermont")
extk_3 <- subset(only_23_and_24, Province_State == "Massachusetts")
extk_4 <- subset(only_23_and_24, Province_State == "Connecticut")
extk_5 <- subset(only_23_and_24, Province_State == "Michigan")
extk_6 <- subset(only_23_and_24, Province_State == "District of Columbia")
extk_7 <- subset(only_23_and_24, Province_State == "Louisiana")
extk_8 <- subset(only_23_and_24, Province_State == "Washington")
extk_9 <- subset(only_23_and_24, Province_State == "New Jersey")
extk_10 <- subset(only_23_and_24, Province_State == "New York")

top_ten_cases_100k <- rbind(extk_1, extk_2, extk_3, extk_4, extk_5, extk_6, extk_7, extk_8, extk_9, extk_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

cases_100k_3_24_bar <- ggplot(top_ten_cases_100k, aes(x = reorder(Province_State, -cases_100k_24), cases_100k_24)) + geom_bar(aes(fill = reorder(Province_State, -cases_100k_24)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),
  panel.border = element_blank(),   
  axis.title.y = element_text(size = 12),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Cases Per 100K Individuals") + ggtitle("Top Ten COVID-19 Confirmed Cases Per 100K Individuals by State 3/24/2020") +
  
   geom_text(aes(label = round(cases_100k_24, 1)), size = 4, position = position_stack(vjust = 0.8))

cases_100k_3_24_bar
```

```{r}
ggsave(filename = "../bar_charts/cases_100k_3_24_bar.png", plot = cases_100k_3_24_bar)
```

```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_23_and_24$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_23_and_24, Province_State == "Indiana")
extp_2 <- subset(only_23_and_24, Province_State == "Missouri")
extp_3 <- subset(only_23_and_24, Province_State == "West Virginia")
extp_4 <- subset(only_23_and_24, Province_State == "Arizona")
extp_5 <- subset(only_23_and_24, Province_State == "North Carolina")
extp_6 <- subset(only_23_and_24, Province_State == "Connecticut")
extp_7 <- subset(only_23_and_24, Province_State == "Massachusetts")
extp_8 <- subset(only_23_and_24, Province_State == "Montana")
extp_9 <- subset(only_23_and_24, Province_State == "Delaware")
extp_10 <- subset(only_23_and_24, Province_State == "Hawaii")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

perc_increase_3_24_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),
  panel.border = element_blank(),   
  axis.title.y = element_text(size = 12),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State from 3/23/20-3/24/20") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

perc_increase_3_24_bar
```

```{r}
ggsave(filename = "../bar_charts/perc_increase_3_24_bar.png", plot = perc_increase_3_24_bar)
```



















