---
title: "three_day_percent_increase"
author: "William Norfolk"
date: "3/26/2020"
output: html_document
---


```{r}
library(tidyverse)
library(readr)
library(maps)
library(usmap)
library(viridis)
```

```{r}
#Load masterdata
covid_master <- readRDS("../clean_covid_data.rds")
```

```{r}
total_pop <- readxl::read_excel("../us_pop.xlsx")
#saveRDS(total_pop, file = "../total_pop.rds")
```

## 4/18/20-4/21/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_18_and_21 <- subset(covid_master, select = c(Province_State, cases_4_18, cases_4_21, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_18_and_21 <- only_18_and_21 %>% dplyr::mutate(percent_increase = (cases_4_21 - cases_4_18) / cases_4_18 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_18_to_21 <- plot_usmap(data = only_18_and_21, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/18/2020-4/21/2020")

p_increase_cases_18_to_21
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_18_to_21.png", plot = p_increase_cases_18_to_21)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_18_and_21$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_18_and_21, Province_State == "Kentucky")
extp_2 <- subset(only_18_and_21, Province_State == "Mississippi")
extp_3 <- subset(only_18_and_21, Province_State == "Kansas")
extp_4 <- subset(only_18_and_21, Province_State == "Virginia")
extp_5 <- subset(only_18_and_21, Province_State == "North Dakota")
extp_6 <- subset(only_18_and_21, Province_State == "Rhode Island")
extp_7 <- subset(only_18_and_21, Province_State == "Ohio")
extp_8 <- subset(only_18_and_21, Province_State == "Nebraska")
extp_9 <- subset(only_18_and_21, Province_State == "Wyoming")
extp_10 <- subset(only_18_and_21, Province_State == "Iowa")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_18_to_4_21_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/18/2020-4/21/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_18_to_4_21_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_18_to_4_21_bar.png", plot = three_day_perc_increase_4_18_to_4_21_bar)
```


## 4/19/20-4/22/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_19_and_22 <- subset(covid_master, select = c(Province_State, cases_4_19, cases_4_22, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_19_and_22 <- only_19_and_22 %>% dplyr::mutate(percent_increase = (cases_4_22 - cases_4_19) / cases_4_19 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_19_to_22 <- plot_usmap(data = only_19_and_22, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/19/2020-4/22/2020")

p_increase_cases_19_to_22
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_19_to_22.png", plot = p_increase_cases_19_to_22)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_19_and_22$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_19_and_22, Province_State == "Virginia")
extp_2 <- subset(only_19_and_22, Province_State == "Ohio")
extp_3 <- subset(only_19_and_22, Province_State == "Kansas")
extp_4 <- subset(only_19_and_22, Province_State == "Nebraska")
extp_5 <- subset(only_19_and_22, Province_State == "Rhode Island")
extp_6 <- subset(only_19_and_22, Province_State == "Connecticut")
extp_7 <- subset(only_19_and_22, Province_State == "Delaware")
extp_8 <- subset(only_19_and_22, Province_State == "Arkansas")
extp_9 <- subset(only_19_and_22, Province_State == "Iowa")
extp_10 <- subset(only_19_and_22, Province_State == "Wyoming")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_19_to_4_22_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/19/2020-4/22/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_19_to_4_22_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_19_to_4_22_bar.png", plot = three_day_perc_increase_4_19_to_4_22_bar)
```



## 4/20/20-4/23/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_20_and_23 <- subset(covid_master, select = c(Province_State, cases_4_20, cases_4_23, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_20_and_23 <- only_20_and_23 %>% dplyr::mutate(percent_increase = (cases_4_23 - cases_4_20) / cases_4_20 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_20_to_23 <- plot_usmap(data = only_20_and_23, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/20/2020-4/23/2020")

p_increase_cases_20_to_23
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_20_to_23.png", plot = p_increase_cases_20_to_23)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_20_and_23$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_20_and_23, Province_State == "Delaware")
extp_2 <- subset(only_20_and_23, Province_State == "New Mexico")
extp_3 <- subset(only_20_and_23, Province_State == "Massachusetts")
extp_4 <- subset(only_20_and_23, Province_State == "Virginia")
extp_5 <- subset(only_20_and_23, Province_State == "Rhode Island")
extp_6 <- subset(only_20_and_23, Province_State == "Iowa")
extp_7 <- subset(only_20_and_23, Province_State == "Arkansas")
extp_8 <- subset(only_20_and_23, Province_State == "Kansas")
extp_9 <- subset(only_20_and_23, Province_State == "Nebraska")
extp_10 <- subset(only_20_and_23, Province_State == "Wyoming")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_20_to_4_23_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/20/2020-4/23/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_20_to_4_23_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_20_to_4_23_bar.png", plot = three_day_perc_increase_4_20_to_4_23_bar)
```



## 4/20/20-4/23/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_21_and_24 <- subset(covid_master, select = c(Province_State, cases_4_21, cases_4_24, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_21_and_24 <- only_21_and_24 %>% dplyr::mutate(percent_increase = (cases_4_24 - cases_4_21) / cases_4_21 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_21_to_24 <- plot_usmap(data = only_21_and_24, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/21/2020-4/24/2020")

p_increase_cases_21_to_24
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_21_to_24.png", plot = p_increase_cases_21_to_24)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_21_and_24$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_21_and_24, Province_State == "Illinois")
extp_2 <- subset(only_21_and_24, Province_State == "Virginia")
extp_3 <- subset(only_21_and_24, Province_State == "Rhode Island")
extp_4 <- subset(only_21_and_24, Province_State == "Iowa")
extp_5 <- subset(only_21_and_24, Province_State == "Massachusetts")
extp_6 <- subset(only_21_and_24, Province_State == "Minnesota")
extp_7 <- subset(only_21_and_24, Province_State == "New Mexico")
extp_8 <- subset(only_21_and_24, Province_State == "Kansas")
extp_9 <- subset(only_21_and_24, Province_State == "Arkansas")
extp_10 <- subset(only_21_and_24, Province_State == "Nebraska")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_21_to_4_24_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/21/2020-4/24/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_21_to_4_24_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_21_to_4_24_bar.png", plot = three_day_perc_increase_4_21_to_4_24_bar)
```

## 4/22/20-4/25/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_22_and_25 <- subset(covid_master, select = c(Province_State, cases_4_22, cases_4_25, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_22_and_25 <- only_22_and_25 %>% dplyr::mutate(percent_increase = (cases_4_25 - cases_4_22) / cases_4_22 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_22_to_25 <- plot_usmap(data = only_22_and_25, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/22/2020-4/25/2020")

p_increase_cases_22_to_25
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_22_to_25.png", plot = p_increase_cases_22_to_25)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_22_and_25$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_22_and_25, Province_State == "New Mexico")
extp_2 <- subset(only_22_and_25, Province_State == "Virginia")
extp_3 <- subset(only_22_and_25, Province_State == "Rhode Island")
extp_4 <- subset(only_22_and_25, Province_State == "Massachusetts")
extp_5 <- subset(only_22_and_25, Province_State == "Tennessee")
extp_6 <- subset(only_22_and_25, Province_State == "Minnesota")
extp_7 <- subset(only_22_and_25, Province_State == "Arkansas")
extp_8 <- subset(only_22_and_25, Province_State == "Kansas")
extp_9 <- subset(only_22_and_25, Province_State == "Iowa")
extp_10 <- subset(only_22_and_25, Province_State == "Nebraska")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_22_to_4_25_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/22/2020-4/25/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_22_to_4_25_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_22_to_4_25_bar.png", plot = three_day_perc_increase_4_22_to_4_25_bar)
```


## 4/23/20-4/26/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_23_and_26 <- subset(covid_master, select = c(Province_State, cases_4_23, cases_4_26, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_23_and_26 <- only_23_and_26 %>% dplyr::mutate(percent_increase = (cases_4_26 - cases_4_23) / cases_4_23 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_23_to_26 <- plot_usmap(data = only_23_and_26, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/23/2020-4/26/2020")

p_increase_cases_23_to_26
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_23_to_26.png", plot = p_increase_cases_23_to_26)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_23_and_26$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_23_and_26, Province_State == "Illinois")
extp_2 <- subset(only_23_and_26, Province_State == "Rhode Island")
extp_3 <- subset(only_23_and_26, Province_State == "Colorado")
extp_4 <- subset(only_23_and_26, Province_State == "Massachusetts")
extp_5 <- subset(only_23_and_26, Province_State == "Kansas")
extp_6 <- subset(only_23_and_26, Province_State == "Delaware")
extp_7 <- subset(only_23_and_26, Province_State == "North Dakota")
extp_8 <- subset(only_23_and_26, Province_State == "Minnesota")
extp_9 <- subset(only_23_and_26, Province_State == "Nebraska")
extp_10 <- subset(only_23_and_26, Province_State == "Iowa")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_23_to_4_26_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/23/2020-4/26/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_23_to_4_26_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_23_to_4_26_bar.png", plot = three_day_perc_increase_4_23_to_4_26_bar)
```

## 4/24/20-4/27/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_24_and_27 <- subset(covid_master, select = c(Province_State, cases_4_24, cases_4_27, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_24_and_27 <- only_24_and_27 %>% dplyr::mutate(percent_increase = (cases_4_27 - cases_4_24) / cases_4_24 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_24_to_27 <- plot_usmap(data = only_24_and_27, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/24/2020-4/27/2020")

p_increase_cases_24_to_27
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_24_to_27.png", plot = p_increase_cases_24_to_27)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_24_and_27$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_24_and_27, Province_State == "Illinois")
extp_2 <- subset(only_24_and_27, Province_State == "Indiana")
extp_3 <- subset(only_24_and_27, Province_State == "Virginia")
extp_4 <- subset(only_24_and_27, Province_State == "Maryland")
extp_5 <- subset(only_24_and_27, Province_State == "Kansas")
extp_6 <- subset(only_24_and_27, Province_State == "Minnesota")
extp_7 <- subset(only_24_and_27, Province_State == "Delaware")
extp_8 <- subset(only_24_and_27, Province_State == "North Dakota")
extp_9 <- subset(only_24_and_27, Province_State == "Iowa")
extp_10 <- subset(only_24_and_27, Province_State == "Nebraska")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_24_to_4_27_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/24/2020-4/27/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_24_to_4_27_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_24_to_4_27_bar.png", plot = three_day_perc_increase_4_24_to_4_27_bar)
```


## 4/25/20-4/28/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_25_and_28 <- subset(covid_master, select = c(Province_State, cases_4_25, cases_4_28, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_25_and_28 <- only_25_and_28 %>% dplyr::mutate(percent_increase = (cases_4_28 - cases_4_25) / cases_4_25 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_25_to_28 <- plot_usmap(data = only_25_and_28, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/25/2020-4/28/2020")

p_increase_cases_25_to_28
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_25_to_28.png", plot = p_increase_cases_25_to_28)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_25_and_28$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_25_and_28, Province_State == "Maryland")
extp_2 <- subset(only_25_and_28, Province_State == "Illinois")
extp_3 <- subset(only_25_and_28, Province_State == "Indiana")
extp_4 <- subset(only_25_and_28, Province_State == "Virginia")
extp_5 <- subset(only_25_and_28, Province_State == "Kansas")
extp_6 <- subset(only_25_and_28, Province_State == "Minnesota")
extp_7 <- subset(only_25_and_28, Province_State == "North Dakota")
extp_8 <- subset(only_25_and_28, Province_State == "Iowa")
extp_9 <- subset(only_25_and_28, Province_State == "Delaware")
extp_10 <- subset(only_25_and_28, Province_State == "Nebraska")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_25_to_4_28_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/25/2020-4/28/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_25_to_4_28_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_25_to_4_28_bar.png", plot = three_day_perc_increase_4_25_to_4_28_bar)
```

## 4/26/20-4/29/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_26_and_29 <- subset(covid_master, select = c(Province_State, cases_4_26, cases_4_29, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_26_and_29 <- only_26_and_29 %>% dplyr::mutate(percent_increase = (cases_4_29 - cases_4_26) / cases_4_26 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_26_to_29 <- plot_usmap(data = only_26_and_29, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/26/2020-4/29/2020")

p_increase_cases_26_to_29
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_26_to_29.png", plot = p_increase_cases_26_to_29)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_26_and_29$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_26_and_29, Province_State == "Indiana")
extp_2 <- subset(only_26_and_29, Province_State == "Illinois")
extp_3 <- subset(only_26_and_29, Province_State == "Virginia")
extp_4 <- subset(only_26_and_29, Province_State == "Delaware")
extp_5 <- subset(only_26_and_29, Province_State == "Kansas")
extp_6 <- subset(only_26_and_29, Province_State == "New Mexico")
extp_7 <- subset(only_26_and_29, Province_State == "North Dakota")
extp_8 <- subset(only_26_and_29, Province_State == "Iowa")
extp_9 <- subset(only_26_and_29, Province_State == "Nebraska")
extp_10 <- subset(only_26_and_29, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_26_to_4_29_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/26/2020-4/29/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_26_to_4_29_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_26_to_4_29_bar.png", plot = three_day_perc_increase_4_26_to_4_29_bar)
```

## 4/27/20-4/30/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_27_and_30 <- subset(covid_master, select = c(Province_State, cases_4_27, cases_4_30, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_27_and_30 <- only_27_and_30 %>% dplyr::mutate(percent_increase = (cases_4_30 - cases_4_27) / cases_4_27 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_27_to_30 <- plot_usmap(data = only_27_and_30, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/27/2020-4/30/2020")

p_increase_cases_27_to_30
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_27_to_30.png", plot = p_increase_cases_27_to_30)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_27_and_30$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_27_and_30, Province_State == "Delaware")
extp_2 <- subset(only_27_and_30, Province_State == "Arizona")
extp_3 <- subset(only_27_and_30, Province_State == "North Carolina")
extp_4 <- subset(only_27_and_30, Province_State == "Illinois")
extp_5 <- subset(only_27_and_30, Province_State == "Virginia")
extp_6 <- subset(only_27_and_30, Province_State == "New Mexico")
extp_7 <- subset(only_27_and_30, Province_State == "Iowa")
extp_8 <- subset(only_27_and_30, Province_State == "Kansas")
extp_9 <- subset(only_27_and_30, Province_State == "Nebraska")
extp_10 <- subset(only_27_and_30, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_27_to_4_30_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/27/2020-4/30/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_27_to_4_30_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_27_to_4_30_bar.png", plot = three_day_perc_increase_4_27_to_4_30_bar)
```


## 4/28/20-5/1/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_28_and_1 <- subset(covid_master, select = c(Province_State, cases_4_28, cases_5_1, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_28_and_1 <- only_28_and_1 %>% dplyr::mutate(percent_increase = (cases_5_1 - cases_4_28) / cases_4_28 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_28_to_1 <- plot_usmap(data = only_28_and_1, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/28/2020-5/1/2020")

p_increase_cases_28_to_1
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_28_to_1.png", plot = p_increase_cases_28_to_1)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_28_and_1$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_28_and_1, Province_State == "Illinois")
extp_2 <- subset(only_28_and_1, Province_State == "District of Columbia")
extp_3 <- subset(only_28_and_1, Province_State == "Maryland")
extp_4 <- subset(only_28_and_1, Province_State == "Virginia")
extp_5 <- subset(only_28_and_1, Province_State == "New Mexico")
extp_6 <- subset(only_28_and_1, Province_State == "Tennessee")
extp_7 <- subset(only_28_and_1, Province_State == "Iowa")
extp_8 <- subset(only_28_and_1, Province_State == "Kansas")
extp_9 <- subset(only_28_and_1, Province_State == "Minnesota")
extp_10 <- subset(only_28_and_1, Province_State == "Nebraska")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_28_to_5_1_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/28/2020-5/1/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_28_to_5_1_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_28_to_5_1_bar.png", plot = three_day_perc_increase_4_28_to_5_1_bar)
```

## 4/29/20-5/2/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_29_and_2 <- subset(covid_master, select = c(Province_State, cases_4_29, cases_5_2, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_29_and_2 <- only_29_and_2 %>% dplyr::mutate(percent_increase = (cases_5_2 - cases_4_29) / cases_4_29 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_29_to_2 <- plot_usmap(data = only_29_and_2, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/29/2020-5/2/2020")

p_increase_cases_29_to_2
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_29_to_2.png", plot = p_increase_cases_29_to_2)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_29_and_2$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_29_and_2, Province_State == "District of Columbia")
extp_2 <- subset(only_29_and_2, Province_State == "Maryland")
extp_3 <- subset(only_29_and_2, Province_State == "Wisconsin")
extp_4 <- subset(only_29_and_2, Province_State == "New Hampshire")
extp_5 <- subset(only_29_and_2, Province_State == "Virginia")
extp_6 <- subset(only_29_and_2, Province_State == "Tennessee")
extp_7 <- subset(only_29_and_2, Province_State == "Iowa")
extp_8 <- subset(only_29_and_2, Province_State == "Kansas")
extp_9 <- subset(only_29_and_2, Province_State == "Minnesota")
extp_10 <- subset(only_29_and_2, Province_State == "Nebraska")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_29_to_5_2_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/29/2020-5/2/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_29_to_5_2_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_29_to_5_2_bar.png", plot = three_day_perc_increase_4_29_to_5_2_bar)
```


## 4/30/20-5/3/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_30_and_3 <- subset(covid_master, select = c(Province_State, cases_4_30, cases_5_3, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_30_and_3 <- only_30_and_3 %>% dplyr::mutate(percent_increase = (cases_5_3 - cases_4_30) / cases_4_30 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_30_to_3 <- plot_usmap(data = only_30_and_3, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 4/30/2020-5/3/2020")

p_increase_cases_30_to_3
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_30_to_3.png", plot = p_increase_cases_30_to_3)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_30_and_3$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_30_and_3, Province_State == "Wisconsin")
extp_2 <- subset(only_30_and_3, Province_State == "Illinois")
extp_3 <- subset(only_30_and_3, Province_State == "Kansas")
extp_4 <- subset(only_30_and_3, Province_State == "Maryland")
extp_5 <- subset(only_30_and_3, Province_State == "New Hampshire")
extp_6 <- subset(only_30_and_3, Province_State == "Virginia")
extp_7 <- subset(only_30_and_3, Province_State == "Tennessee")
extp_8 <- subset(only_30_and_3, Province_State == "Iowa")
extp_9 <- subset(only_30_and_3, Province_State == "Minnesota")
extp_10 <- subset(only_30_and_3, Province_State == "Nebraska")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_4_30_to_5_3_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 4/30/2020-5/3/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_4_30_to_5_3_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_4_30_to_5_3_bar.png", plot = three_day_perc_increase_4_30_to_5_3_bar)
```

## 5/01/20-5/4/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_1_and_4 <- subset(covid_master, select = c(Province_State, cases_5_1, cases_5_4, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_1_and_4 <- only_1_and_4 %>% dplyr::mutate(percent_increase = (cases_5_4 - cases_5_1) / cases_5_1 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_1_to_4 <- plot_usmap(data = only_1_and_4, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/1/2020-5/4/2020")

p_increase_cases_1_to_4
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_1_to_4.png", plot = p_increase_cases_1_to_4)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_1_and_4$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_1_and_4, Province_State == "Maryland")
extp_2 <- subset(only_1_and_4, Province_State == "Wisconsin")
extp_3 <- subset(only_1_and_4, Province_State == "Illinois")
extp_4 <- subset(only_1_and_4, Province_State == "Tennessee")
extp_5 <- subset(only_1_and_4, Province_State == "New Mexico")
extp_6 <- subset(only_1_and_4, Province_State == "Virginia")
extp_7 <- subset(only_1_and_4, Province_State == "Kansas")
extp_8 <- subset(only_1_and_4, Province_State == "Nebraska")
extp_9 <- subset(only_1_and_4, Province_State == "Iowa")
extp_10 <- subset(only_1_and_4, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_1_to_5_4_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/1/2020-5/4/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_1_to_5_4_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_1_to_5_4_bar.png", plot = three_day_perc_increase_5_1_to_5_4_bar)
```


## 5/02/20-5/5/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_2_and_5 <- subset(covid_master, select = c(Province_State, cases_5_2, cases_5_5, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_2_and_5 <- only_2_and_5 %>% dplyr::mutate(percent_increase = (cases_5_5 - cases_5_2) / cases_5_2 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_2_to_5 <- plot_usmap(data = only_2_and_5, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/2/2020-5/5/2020")

p_increase_cases_2_to_5
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_2_to_5.png", plot = p_increase_cases_2_to_5)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_2_and_5$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_2_and_5, Province_State == "District of Columbia")
extp_2 <- subset(only_2_and_5, Province_State == "Arizona")
extp_3 <- subset(only_2_and_5, Province_State == "Wisconsin")
extp_4 <- subset(only_2_and_5, Province_State == "Illinois")
extp_5 <- subset(only_2_and_5, Province_State == "Virginia")
extp_6 <- subset(only_2_and_5, Province_State == "Kansas")
extp_7 <- subset(only_2_and_5, Province_State == "Iowa")
extp_8 <- subset(only_2_and_5, Province_State == "Kentucky")
extp_9 <- subset(only_2_and_5, Province_State == "Nebraska")
extp_10 <- subset(only_2_and_5, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_2_to_5_5_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/2/2020-5/5/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_2_to_5_5_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_2_to_5_5_bar.png", plot = three_day_perc_increase_5_2_to_5_5_bar)
```

## 5/03/20-5/6/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_3_and_6 <- subset(covid_master, select = c(Province_State, cases_5_3, cases_5_6, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_3_and_6 <- only_3_and_6 %>% dplyr::mutate(percent_increase = (cases_5_6 - cases_5_3) / cases_5_3 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_3_to_6 <- plot_usmap(data = only_3_and_6, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/3/2020-5/6/2020")

p_increase_cases_3_to_6
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_3_to_6.png", plot = p_increase_cases_3_to_6)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_3_and_6$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_3_and_6, Province_State == "North Dakota")
extp_2 <- subset(only_3_and_6, Province_State == "New Mexico")
extp_3 <- subset(only_3_and_6, Province_State == "Mississippi")
extp_4 <- subset(only_3_and_6, Province_State == "Wisconsin")
extp_5 <- subset(only_3_and_6, Province_State == "Arizona")
extp_6 <- subset(only_3_and_6, Province_State == "Iowa")
extp_7 <- subset(only_3_and_6, Province_State == "Kentucky")
extp_8 <- subset(only_3_and_6, Province_State == "Kansas")
extp_9 <- subset(only_3_and_6, Province_State == "Nebraska")
extp_10 <- subset(only_3_and_6, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_3_to_5_6_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/3/2020-5/6/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_3_to_5_6_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_3_to_5_6_bar.png", plot = three_day_perc_increase_5_3_to_5_6_bar)
```


## 5/04/20-5/7/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_4_and_7 <- subset(covid_master, select = c(Province_State, cases_5_4, cases_5_7, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_4_and_7 <- only_4_and_7 %>% dplyr::mutate(percent_increase = (cases_5_7 - cases_5_4) / cases_5_4 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_4_to_7 <- plot_usmap(data = only_4_and_7, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/4/2020-5/7/2020")

p_increase_cases_4_to_7
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_4_to_7.png", plot = p_increase_cases_4_to_7)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_4_and_7$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_4_and_7, Province_State == "Alabama")
extp_2 <- subset(only_4_and_7, Province_State == "Wisconsin")
extp_3 <- subset(only_4_and_7, Province_State == "North Dakota")
extp_4 <- subset(only_4_and_7, Province_State == "Delaware")
extp_5 <- subset(only_4_and_7, Province_State == "North Carolina")
extp_6 <- subset(only_4_and_7, Province_State == "Iowa")
extp_7 <- subset(only_4_and_7, Province_State == "Kentucky")
extp_8 <- subset(only_4_and_7, Province_State == "Kansas")
extp_9 <- subset(only_4_and_7, Province_State == "Nebraska")
extp_10 <- subset(only_4_and_7, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_4_to_5_7_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/4/2020-5/7/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_4_to_5_7_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_4_to_5_7_bar.png", plot = three_day_perc_increase_5_4_to_5_7_bar)
```



## 5/05/20-5/8/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_5_and_8 <- subset(covid_master, select = c(Province_State, cases_5_5, cases_5_8, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_5_and_8 <- only_5_and_8 %>% dplyr::mutate(percent_increase = (cases_5_8 - cases_5_5) / cases_5_5 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_5_to_8 <- plot_usmap(data = only_5_and_8, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/5/2020-5/8/2020")

p_increase_cases_5_to_8
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_5_to_8.png", plot = p_increase_cases_5_to_8)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_5_and_8$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_5_and_8, Province_State == "Maryland")
extp_2 <- subset(only_5_and_8, Province_State == "North Dakota")
extp_3 <- subset(only_5_and_8, Province_State == "New Mexico")
extp_4 <- subset(only_5_and_8, Province_State == "Arizona")
extp_5 <- subset(only_5_and_8, Province_State == "Iowa")
extp_6 <- subset(only_5_and_8, Province_State == "Delaware")
extp_7 <- subset(only_5_and_8, Province_State == "South Dakota")
extp_8 <- subset(only_5_and_8, Province_State == "Kansas")
extp_9 <- subset(only_5_and_8, Province_State == "Nebraska")
extp_10 <- subset(only_5_and_8, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_5_to_5_8_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/5/2020-5/8/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_5_to_5_8_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_5_to_5_8_bar.png", plot = three_day_perc_increase_5_5_to_5_8_bar)
```



## 5/06/20-5/9/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_6_and_9 <- subset(covid_master, select = c(Province_State, cases_5_6, cases_5_9, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_6_and_9 <- only_6_and_9 %>% dplyr::mutate(percent_increase = (cases_5_9 - cases_5_6) / cases_5_6 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_6_to_9 <- plot_usmap(data = only_6_and_9, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/6/2020-5/9/2020")

p_increase_cases_6_to_9
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_6_to_9.png", plot = p_increase_cases_6_to_9)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_6_and_9$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_6_and_9, Province_State == "District of Columbia")
extp_2 <- subset(only_6_and_9, Province_State == "Maryland")
extp_3 <- subset(only_6_and_9, Province_State == "Iowa")
extp_4 <- subset(only_6_and_9, Province_State == "Maine")
extp_5 <- subset(only_6_and_9, Province_State == "Arizona")
extp_6 <- subset(only_6_and_9, Province_State == "Kansas")
extp_7 <- subset(only_6_and_9, Province_State == "Virginia")
extp_8 <- subset(only_6_and_9, Province_State == "Nebraska")
extp_9 <- subset(only_6_and_9, Province_State == "South Dakota")
extp_10 <- subset(only_6_and_9, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_6_to_5_9_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/6/2020-5/9/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_6_to_5_9_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_6_to_5_9_bar.png", plot = three_day_perc_increase_5_6_to_5_9_bar)
```

## 5/07/20-5/10/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_7_and_10 <- subset(covid_master, select = c(Province_State, cases_5_7, cases_5_10, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_7_and_10 <- only_7_and_10 %>% dplyr::mutate(percent_increase = (cases_5_10 - cases_5_7) / cases_5_7 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_7_to_10 <- plot_usmap(data = only_7_and_10, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/7/2020-5/10/2020")

p_increase_cases_7_to_10
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_7_to_10.png", plot = p_increase_cases_7_to_10)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_7_and_10$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_7_and_10, Province_State == "Kansas")
extp_2 <- subset(only_7_and_10, Province_State == "North Carolina")
extp_3 <- subset(only_7_and_10, Province_State == "Wisconsin")
extp_4 <- subset(only_7_and_10, Province_State == "District of Columbia")
extp_5 <- subset(only_7_and_10, Province_State == "Maryland")
extp_6 <- subset(only_7_and_10, Province_State == "Nebraska")
extp_7 <- subset(only_7_and_10, Province_State == "Virginia")
extp_8 <- subset(only_7_and_10, Province_State == "Arizona")
extp_9 <- subset(only_7_and_10, Province_State == "Minnesota")
extp_10 <- subset(only_7_and_10, Province_State == "South Dakota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_7_to_5_10_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/7/2020-5/10/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_7_to_5_10_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_7_to_5_10_bar.png", plot = three_day_perc_increase_5_7_to_5_10_bar)
```


## 5/08/20-5/11/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_8_and_11 <- subset(covid_master, select = c(Province_State, cases_5_8, cases_5_11, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_8_and_11 <- only_8_and_11 %>% dplyr::mutate(percent_increase = (cases_5_11 - cases_5_8) / cases_5_8 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_8_to_11 <- plot_usmap(data = only_8_and_11, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/8/2020-5/11/2020")

p_increase_cases_8_to_11
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_8_to_11.png", plot = p_increase_cases_8_to_11)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_8_and_11$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_8_and_11, Province_State == "District of Columbia")
extp_2 <- subset(only_8_and_11, Province_State == "New Mexico")
extp_3 <- subset(only_8_and_11, Province_State == "Wisconsin")
extp_4 <- subset(only_8_and_11, Province_State == "California")
extp_5 <- subset(only_8_and_11, Province_State == "Texas")
extp_6 <- subset(only_8_and_11, Province_State == "North Carolina")
extp_7 <- subset(only_8_and_11, Province_State == "Maryland")
extp_8 <- subset(only_8_and_11, Province_State == "Virginia")
extp_9 <- subset(only_8_and_11, Province_State == "South Dakota")
extp_10 <- subset(only_8_and_11, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_8_to_5_11_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/8/2020-5/11/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_8_to_5_11_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_8_to_5_11_bar.png", plot = three_day_perc_increase_5_8_to_5_11_bar)
```

## 5/09/20-5/12/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_9_and_12 <- subset(covid_master, select = c(Province_State, cases_5_9, cases_5_12, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_9_and_12 <- only_9_and_12 %>% dplyr::mutate(percent_increase = (cases_5_12 - cases_5_9) / cases_5_9 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_9_to_12 <- plot_usmap(data = only_9_and_12, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/9/2020-5/12/2020")

p_increase_cases_9_to_12
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_9_to_12.png", plot = p_increase_cases_9_to_12)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_9_and_12$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_9_and_12, Province_State == "South Dakota")
extp_2 <- subset(only_9_and_12, Province_State == "Maryland")
extp_3 <- subset(only_9_and_12, Province_State == "Alabama")
extp_4 <- subset(only_9_and_12, Province_State == "New Mexico")
extp_5 <- subset(only_9_and_12, Province_State == "Tennessee")
extp_6 <- subset(only_9_and_12, Province_State == "Illinois")
extp_7 <- subset(only_9_and_12, Province_State == "Iowa")
extp_8 <- subset(only_9_and_12, Province_State == "Arkansas")
extp_9 <- subset(only_9_and_12, Province_State == "Virginia")
extp_10 <- subset(only_9_and_12, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_9_to_5_12_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/9/2020-5/12/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_9_to_5_12_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_9_to_5_12_bar.png", plot = three_day_perc_increase_5_9_to_5_12_bar)
```

## 5/10/20-5/13/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_10_and_13 <- subset(covid_master, select = c(Province_State, cases_5_10, cases_5_13, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_10_and_13 <- only_10_and_13 %>% dplyr::mutate(percent_increase = (cases_5_13 - cases_5_10) / cases_5_10 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_10_to_13 <- plot_usmap(data = only_10_and_13, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/10/2020-5/13/2020")

p_increase_cases_10_to_13
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_10_to_13.png", plot = p_increase_cases_10_to_13)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_10_and_13$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_10_and_13, Province_State == "Tennessee")
extp_2 <- subset(only_10_and_13, Province_State == "North Carolina")
extp_3 <- subset(only_10_and_13, Province_State == "Texas")
extp_4 <- subset(only_10_and_13, Province_State == "Arizona")
extp_5 <- subset(only_10_and_13, Province_State == "New Mexico")
extp_6 <- subset(only_10_and_13, Province_State == "North Dakota")
extp_7 <- subset(only_10_and_13, Province_State == "Delaware")
extp_8 <- subset(only_10_and_13, Province_State == "Virginia")
extp_9 <- subset(only_10_and_13, Province_State == "Iowa")
extp_10 <- subset(only_10_and_13, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_10_to_5_13_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/10/2020-5/13/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_10_to_5_13_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_10_to_5_13_bar.png", plot = three_day_perc_increase_5_10_to_5_13_bar)
```


## 5/11/20-5/14/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_11_and_14 <- subset(covid_master, select = c(Province_State, cases_5_11, cases_5_14, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_11_and_14 <- only_11_and_14 %>% dplyr::mutate(percent_increase = (cases_5_14 - cases_5_11) / cases_5_11 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_11_to_14 <- plot_usmap(data = only_11_and_14, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/11/2020-5/14/2020")

p_increase_cases_11_to_14
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_11_to_14.png", plot = p_increase_cases_11_to_14)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_11_and_14$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_11_and_14, Province_State == "Texas")
extp_2 <- subset(only_11_and_14, Province_State == "Delaware")
extp_3 <- subset(only_11_and_14, Province_State == "Nebraska")
extp_4 <- subset(only_11_and_14, Province_State == "Iowa")
extp_5 <- subset(only_11_and_14, Province_State == "Virginia")
extp_6 <- subset(only_11_and_14, Province_State == "North Carolina")
extp_7 <- subset(only_11_and_14, Province_State == "Illinois")
extp_8 <- subset(only_11_and_14, Province_State == "Arizona")
extp_9 <- subset(only_11_and_14, Province_State == "North Dakota")
extp_10 <- subset(only_11_and_14, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_11_to_5_14_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/11/2020-5/14/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_11_to_5_14_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_11_to_5_14_bar.png", plot = three_day_perc_increase_5_11_to_5_14_bar)
```


## 5/12/20-5/15/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_12_and_15 <- subset(covid_master, select = c(Province_State, cases_5_12, cases_5_15, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_12_and_15 <- only_12_and_15 %>% dplyr::mutate(percent_increase = (cases_5_15 - cases_5_12) / cases_5_12 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_12_to_15 <- plot_usmap(data = only_12_and_15, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/12/2020-5/15/2020")

p_increase_cases_12_to_15
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_12_to_15.png", plot = p_increase_cases_12_to_15)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_12_and_15$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_12_and_15, Province_State == "Mississippi")
extp_2 <- subset(only_12_and_15, Province_State == "Delaware")
extp_3 <- subset(only_12_and_15, Province_State == "Wisconsin")
extp_4 <- subset(only_12_and_15, Province_State == "Texas")
extp_5 <- subset(only_12_and_15, Province_State == "Virginia")
extp_6 <- subset(only_12_and_15, Province_State == "North Carolina")
extp_7 <- subset(only_12_and_15, Province_State == "North Dakota")
extp_8 <- subset(only_12_and_15, Province_State == "Arizona")
extp_9 <- subset(only_12_and_15, Province_State == "Nebraska")
extp_10 <- subset(only_12_and_15, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_12_to_5_15_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/12/2020-5/15/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_12_to_5_15_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_12_to_5_15_bar.png", plot = three_day_perc_increase_5_12_to_5_15_bar)
```

## 5/13/20-5/16/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_13_and_16 <- subset(covid_master, select = c(Province_State, cases_5_13, cases_5_16, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_13_and_16 <- only_13_and_16 %>% dplyr::mutate(percent_increase = (cases_5_16 - cases_5_13) / cases_5_13 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_13_to_16 <- plot_usmap(data = only_13_and_16, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/13/2020-5/16/2020")

p_increase_cases_13_to_16
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_13_to_16.png", plot = p_increase_cases_13_to_16)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_13_and_16$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_13_and_16, Province_State == "Mississippi")
extp_2 <- subset(only_13_and_16, Province_State == "Texas")
extp_3 <- subset(only_13_and_16, Province_State == "North Carolina")
extp_4 <- subset(only_13_and_16, Province_State == "Virginia")
extp_5 <- subset(only_13_and_16, Province_State == "Wisconsin")
extp_6 <- subset(only_13_and_16, Province_State == "Arizona")
extp_7 <- subset(only_13_and_16, Province_State == "Kentucky")
extp_8 <- subset(only_13_and_16, Province_State == "North Dakota")
extp_9 <- subset(only_13_and_16, Province_State == "Nebraska")
extp_10 <- subset(only_13_and_16, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_13_to_5_16_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/13/2020-5/16/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_13_to_5_16_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_13_to_5_16_bar.png", plot = three_day_perc_increase_5_13_to_5_16_bar)
```

## 5/14/20-5/17/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_14_and_17 <- subset(covid_master, select = c(Province_State, cases_5_14, cases_5_17, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_14_and_17 <- only_14_and_17 %>% dplyr::mutate(percent_increase = (cases_5_17 - cases_5_14) / cases_5_14 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_14_to_17 <- plot_usmap(data = only_14_and_17, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/14/2020-5/17/2020")

p_increase_cases_14_to_17
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_14_to_17.png", plot = p_increase_cases_14_to_17)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_14_and_17$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_14_and_17, Province_State == "Maryland")
extp_2 <- subset(only_14_and_17, Province_State == "Texas")
extp_3 <- subset(only_14_and_17, Province_State == "Arkansas")
extp_4 <- subset(only_14_and_17, Province_State == "Virginia")
extp_5 <- subset(only_14_and_17, Province_State == "Nebraska")
extp_6 <- subset(only_14_and_17, Province_State == "Arizona")
extp_7 <- subset(only_14_and_17, Province_State == "North Carolina")
extp_8 <- subset(only_14_and_17, Province_State == "North Dakota")
extp_9 <- subset(only_14_and_17, Province_State == "Wisconsin")
extp_10 <- subset(only_14_and_17, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_14_to_5_17_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/14/2020-5/17/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_14_to_5_17_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_14_to_5_17_bar.png", plot = three_day_perc_increase_5_14_to_5_17_bar)
```


## 5/15/20-5/18/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_15_and_18 <- subset(covid_master, select = c(Province_State, cases_5_15, cases_5_18, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_15_and_18 <- only_15_and_18 %>% dplyr::mutate(percent_increase = (cases_5_18 - cases_5_15) / cases_5_15 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_15_to_18 <- plot_usmap(data = only_15_and_18, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/15/2020-5/18/2020")

p_increase_cases_15_to_18
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_15_to_18.png", plot = p_increase_cases_15_to_18)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_15_and_18$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_15_and_18, Province_State == "Texas")
extp_2 <- subset(only_15_and_18, Province_State == "New Mexico")
extp_3 <- subset(only_15_and_18, Province_State == "Arkansas")
extp_4 <- subset(only_15_and_18, Province_State == "Arizona")
extp_5 <- subset(only_15_and_18, Province_State == "Wisconsin")
extp_6 <- subset(only_15_and_18, Province_State == "Virginia")
extp_7 <- subset(only_15_and_18, Province_State == "North Carolina")
extp_8 <- subset(only_15_and_18, Province_State == "North Dakota")
extp_9 <- subset(only_15_and_18, Province_State == "Nebraska")
extp_10 <- subset(only_15_and_18, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_15_to_5_18_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/15/2020-5/18/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_15_to_5_18_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_15_to_5_18_bar.png", plot = three_day_perc_increase_5_15_to_5_18_bar)
```

## 5/16/20-5/19/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_16_and_19 <- subset(covid_master, select = c(Province_State, cases_5_16, cases_5_19, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_16_and_19 <- only_16_and_19 %>% dplyr::mutate(percent_increase = (cases_5_19 - cases_5_16) / cases_5_16 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_16_to_19 <- plot_usmap(data = only_16_and_19, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/16/2020-5/19/2020")

p_increase_cases_16_to_19
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_16_to_19.png", plot = p_increase_cases_16_to_19)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_16_and_19$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_16_and_19, Province_State == "Delaware")
extp_2 <- subset(only_16_and_19, Province_State == "Texas")
extp_3 <- subset(only_16_and_19, Province_State == "Tennessee")
extp_4 <- subset(only_16_and_19, Province_State == "Arizona")
extp_5 <- subset(only_16_and_19, Province_State == "Iowa")
extp_6 <- subset(only_16_and_19, Province_State == "Arkansas")
extp_7 <- subset(only_16_and_19, Province_State == "North Dakota")
extp_8 <- subset(only_16_and_19, Province_State == "Virginia")
extp_9 <- subset(only_16_and_19, Province_State == "Maryland")
extp_10 <- subset(only_16_and_19, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_16_to_5_19_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/16/2020-5/19/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_16_to_5_19_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_16_to_5_19_bar.png", plot = three_day_perc_increase_5_16_to_5_19_bar)
```


## 5/17/20-5/20/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_17_and_20 <- subset(covid_master, select = c(Province_State, cases_5_17, cases_5_20, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_17_and_20 <- only_17_and_20 %>% dplyr::mutate(percent_increase = (cases_5_20 - cases_5_17) / cases_5_17 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_17_to_20 <- plot_usmap(data = only_17_and_20, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/17/2020-5/20/2020")

p_increase_cases_17_to_20
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_17_to_20.png", plot = p_increase_cases_17_to_20)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_17_and_20$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_17_and_20, Province_State == "California")
extp_2 <- subset(only_17_and_20, Province_State == "New Hampshire")
extp_3 <- subset(only_17_and_20, Province_State == "Maine")
extp_4 <- subset(only_17_and_20, Province_State == "Virginia")
extp_5 <- subset(only_17_and_20, Province_State == "North Carolina")
extp_6 <- subset(only_17_and_20, Province_State == "Maryland")
extp_7 <- subset(only_17_and_20, Province_State == "Nebraska")
extp_8 <- subset(only_17_and_20, Province_State == "North Dakota")
extp_9 <- subset(only_17_and_20, Province_State == "Alabama")
extp_10 <- subset(only_17_and_20, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_17_to_5_20_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/17/2020-5/20/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_17_to_5_20_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_17_to_5_20_bar.png", plot = three_day_perc_increase_5_17_to_5_20_bar)
```


## 5/18/20-5/21/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_18_and_21 <- subset(covid_master, select = c(Province_State, cases_5_18, cases_5_21, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_18_and_21 <- only_18_and_21 %>% dplyr::mutate(percent_increase = (cases_5_21 - cases_5_18) / cases_5_18 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_18_to_21 <- plot_usmap(data = only_18_and_21, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/18/2020-5/21/2020")

p_increase_cases_18_to_21
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_18_to_21.png", plot = p_increase_cases_18_to_21)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_18_and_21$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_18_and_21, Province_State == "California")
extp_2 <- subset(only_18_and_21, Province_State == "Iowa")
extp_3 <- subset(only_18_and_21, Province_State == "Wisconsin")
extp_4 <- subset(only_18_and_21, Province_State == "Maryland")
extp_5 <- subset(only_18_and_21, Province_State == "Maine")
extp_6 <- subset(only_18_and_21, Province_State == "Virginia")
extp_7 <- subset(only_18_and_21, Province_State == "Alabama")
extp_8 <- subset(only_18_and_21, Province_State == "Minnesota")
extp_9 <- subset(only_18_and_21, Province_State == "Arkansas")
extp_10 <- subset(only_18_and_21, Province_State == "North Dakota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_18_to_5_21_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/18/2020-5/21/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_18_to_5_21_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_18_to_5_21_bar.png", plot = three_day_perc_increase_5_18_to_5_21_bar)
```


## 5/19/20-5/22/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_19_and_22 <- subset(covid_master, select = c(Province_State, cases_5_19, cases_5_22, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_19_and_22 <- only_19_and_22 %>% dplyr::mutate(percent_increase = (cases_5_22 - cases_5_19) / cases_5_19 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_19_to_22 <- plot_usmap(data = only_19_and_22, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/19/2020-5/22/2020")

p_increase_cases_19_to_22
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_19_to_22.png", plot = p_increase_cases_19_to_22)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_19_and_22$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_19_and_22, Province_State == "New Hampshire")
extp_2 <- subset(only_19_and_22, Province_State == "Virginia")
extp_3 <- subset(only_19_and_22, Province_State == "Alabama")
extp_4 <- subset(only_19_and_22, Province_State == "Minnesota")
extp_5 <- subset(only_19_and_22, Province_State == "Wisconsin")
extp_6 <- subset(only_19_and_22, Province_State == "Maine")
extp_7 <- subset(only_19_and_22, Province_State == "West Virginia")
extp_8 <- subset(only_19_and_22, Province_State == "Arkansas")
extp_9 <- subset(only_19_and_22, Province_State == "North Carolina")
extp_10 <- subset(only_19_and_22, Province_State == "North Dakota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_19_to_5_22_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/19/2020-5/22/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_19_to_5_22_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_19_to_5_22_bar.png", plot = three_day_perc_increase_5_19_to_5_22_bar)
```


## 5/20/20-5/23/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_20_and_23 <- subset(covid_master, select = c(Province_State, cases_5_20, cases_5_23, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_20_and_23 <- only_20_and_23 %>% dplyr::mutate(percent_increase = (cases_5_23 - cases_5_20) / cases_5_20 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_20_to_23 <- plot_usmap(data = only_20_and_23, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/20/2020-5/23/2020")

p_increase_cases_20_to_23
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_20_to_23.png", plot = p_increase_cases_20_to_23)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_20_and_23$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_20_and_23, Province_State == "Iowa")
extp_2 <- subset(only_20_and_23, Province_State == "Virginia")
extp_3 <- subset(only_20_and_23, Province_State == "Mississippi")
extp_4 <- subset(only_20_and_23, Province_State == "West Virginia")
extp_5 <- subset(only_20_and_23, Province_State == "Maine")
extp_6 <- subset(only_20_and_23, Province_State == "Wisconsin")
extp_7 <- subset(only_20_and_23, Province_State == "Minnesota")
extp_8 <- subset(only_20_and_23, Province_State == "North Carolina")
extp_9 <- subset(only_20_and_23, Province_State == "North Dakota")
extp_10 <- subset(only_20_and_23, Province_State == "Arkansas")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_20_to_5_23_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/20/2020-5/23/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_20_to_5_23_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_20_to_5_23_bar.png", plot = three_day_perc_increase_5_20_to_5_23_bar)
```


## 5/21/20-5/24/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_21_and_24 <- subset(covid_master, select = c(Province_State, cases_5_21, cases_5_24, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_21_and_24 <- only_21_and_24 %>% dplyr::mutate(percent_increase = (cases_5_24 - cases_5_21) / cases_5_21 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_21_to_24 <- plot_usmap(data = only_21_and_24, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/21/2020-5/24/2020")

p_increase_cases_21_to_24
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_21_to_24.png", plot = p_increase_cases_21_to_24)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_21_and_24$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_21_and_24, Province_State == "North Dakota")
extp_2 <- subset(only_21_and_24, Province_State == "Mississippi")
extp_3 <- subset(only_21_and_24, Province_State == "Arkansas")
extp_4 <- subset(only_21_and_24, Province_State == "Alabama")
extp_5 <- subset(only_21_and_24, Province_State == "South Dakota")
extp_6 <- subset(only_21_and_24, Province_State == "Maine")
extp_7 <- subset(only_21_and_24, Province_State == "Wisconsin")
extp_8 <- subset(only_21_and_24, Province_State == "West Virginia")
extp_9 <- subset(only_21_and_24, Province_State == "Minnesota")
extp_10 <- subset(only_21_and_24, Province_State == "North Carolina")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_21_to_5_24_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/21/2020-5/24/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_21_to_5_24_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_21_to_5_24_bar.png", plot = three_day_perc_increase_5_21_to_5_24_bar)
```


## 5/22/20-5/25/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_22_and_25 <- subset(covid_master, select = c(Province_State, cases_5_22, cases_5_25, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_22_and_25 <- only_22_and_25 %>% dplyr::mutate(percent_increase = (cases_5_25 - cases_5_22) / cases_5_22 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_22_to_25 <- plot_usmap(data = only_22_and_25, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/22/2020-5/25/2020")

p_increase_cases_22_to_25
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_22_to_25.png", plot = p_increase_cases_22_to_25)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_22_and_25$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_22_and_25, Province_State == "Iowa")
extp_2 <- subset(only_22_and_25, Province_State == "Maine")
extp_3 <- subset(only_22_and_25, Province_State == "Mississippi")
extp_4 <- subset(only_22_and_25, Province_State == "California")
extp_5 <- subset(only_22_and_25, Province_State == "Arkansas")
extp_6 <- subset(only_22_and_25, Province_State == "Virginia")
extp_7 <- subset(only_22_and_25, Province_State == "Wisconsin")
extp_8 <- subset(only_22_and_25, Province_State == "North Carolina")
extp_9 <- subset(only_22_and_25, Province_State == "Alabama")
extp_10 <- subset(only_22_and_25, Province_State == "Minnesota")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_22_to_5_25_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/22/2020-5/25/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_22_to_5_25_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_22_to_5_25_bar.png", plot = three_day_perc_increase_5_22_to_5_25_bar)
```


## 5/23/20-5/26/20


```{r}
#To determine percent increase from prior day, include only last two observations
#MODIFY: object dates and variable dates.

only_23_and_26 <- subset(covid_master, select = c(Province_State, cases_5_23, cases_5_26, fips, total_pop))
```


```{r}
#add percent increase
#MODIFY: object dates and variable dates.

only_23_and_26 <- only_23_and_26 %>% dplyr::mutate(percent_increase = (cases_5_26 - cases_5_23) / cases_5_23 * 100)
```

```{r}
#make heatmap of percent increase

p_increase_cases_23_to_26 <- plot_usmap(data = only_23_and_26, values = "percent_increase", color = "black") + 
  
  scale_fill_continuous(low = "white", high = "red", name = "Percent Increase", label = scales::comma) + theme(legend.position = "right", plot.title = element_text(color = "black", size = 15, face = "bold"), plot.subtitle = element_text(color = "black", size = 10, face = "italic")) + labs(title = "Percent Increase of Confirmed COVID-19 Cases by State", subtitle = "From: 5/23/2020-5/26/2020")

p_increase_cases_23_to_26
```

```{r}
ggsave(filename = "../heat_maps/p_increase_cases_23_to_26.png", plot = p_increase_cases_23_to_26)
```


```{r}
#Take a look at the top 10 percent increases
#MODIFY: cases variable for new date
tail(sort(only_23_and_26$percent_increase ),10)
```

```{r}
#subset top 10 cases
#subset top 10 100K
#MODIFY: must search ten above individually (subset does not allow to select by these values for some reason...) and past the states in the code below.Also modify variable and object date names.

extp_1 <- subset(only_23_and_26, Province_State == "Delaware")
extp_2 <- subset(only_23_and_26, Province_State == "Wisconsin")
extp_3 <- subset(only_23_and_26, Province_State == "North Carolina")
extp_4 <- subset(only_23_and_26, Province_State == "Arkansas")
extp_5 <- subset(only_23_and_26, Province_State == "Nevada")
extp_6 <- subset(only_23_and_26, Province_State == "California")
extp_7 <- subset(only_23_and_26, Province_State == "New Mexico")
extp_8 <- subset(only_23_and_26, Province_State == "Virginia")
extp_9 <- subset(only_23_and_26, Province_State == "Minnesota")
extp_10 <- subset(only_23_and_26, Province_State == "Alabama")

top_ten_perc_increase <- rbind(extp_1, extp_2, extp_3, extp_4, extp_5, extp_6, extp_7, extp_8, extp_9, extp_10)
```

```{r}
#make bar chart
#Modify: object dates and variable dates

three_day_perc_increase_5_23_to_5_26_bar <- ggplot(top_ten_perc_increase, aes(x = reorder(Province_State, -percent_increase), percent_increase)) + geom_bar(aes(fill = reorder(Province_State, -percent_increase)), stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                                                                                   legend.position = "none",                                                                        axis.text=element_text(size=12),                                                                 axis.title.y = element_text(size = 12),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  panel.background = element_blank()) + xlab("") + ylab("Percent Increase") + ggtitle("COVID-19: Top Ten Percent Increase by State From 5/23/2020-5/26/2020") +
  
   geom_text(aes(label = round(percent_increase, 2)), size = 4, position = position_stack(vjust = 0.8))

three_day_perc_increase_5_23_to_5_26_bar
```

```{r}
ggsave(filename = "../bar_charts/three_day_perc_increase_5_23_to_5_26_bar.png", plot = three_day_perc_increase_5_23_to_5_26_bar)
```